# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://coadroad.io
title: CodeRoad
email: shawn.j.mckay@gmail.com
author: Shawn McKay
description: > # "Free interactive coding tutorials inside of the Atom editor. Build your own tutorials
using the coderoad-cli and tools developers already know: markdown and unit tests.
copyright: 'Copyright &copy; 2016 Shawn McKay. All Rights Reserved.'
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: coderoad CLI
    icon: github
    url: https://github.com/coderoad/coderoad-cli
  - title: atom plugin
    icon: github
    url: https://github.com/coderoad/atom-coderoad
