# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://coderoad.github.io
title: CodeRoad
email: coderoadapp@gmail.com
author: Shawn McKay
description: > # "Free interactive coding tutorials inside of the Atom editor. Build your own tutorials
using the coderoad-cli and tools developers already know: markdown and unit tests.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

gems:
  - jekyll-sitemap
  - rouge

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

tutorials:
  - title: Functional School
    description: A fun look at functional programming concepts in JavaScript
    icon: github
    url: https://github.com/coderoad/coderoad-functional-school
    instructions: npm i -s coderoad-functional-school
